common/models/MasterNews.php
<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "master_news".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property integer $page_id
 * @property string $news_name
 * @property string $news_title
 * @property string $news_content
 * @property string $news_pict
 * @property string $news_alt
 * @property integer $isactive
 * @property integer $sort_no
 * @property string $news_date
 * @property string $effective_from
 * @property string $effective_till
 * @property integer $createdby
 * @property string $createdon
 * @property integer $lastmodifby
 * @property string $lastmodif
 * @property integer $status
 *
 * @property CustUsers $createdby0
 * @property MasterCustomer $customer
 * @property CustUsers $lastmodifby0
 * @property MasterPages $page
 * @property MasterNewsPictures[] $masterNewsPictures
 */
class MasterNews extends \yii\db\ActiveRecord
{
    public $getfile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_news';
    }

    public function behaviors()
    {
        //Yii::$app->formatter->asDate('now', 'php:Y-m-d H:i:s');
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdon',
                'updatedAtAttribute' => 'lastmodif',
                'value'=> new Expression('NOW()'),
                //'value' => Yii::$app->formatter->asDatetime(date('yyyy-mm-dd H:i:s'))
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'createdby',
                'updatedByAttribute' => 'lastmodifby',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id'], 'required'],
            [['customer_id', 'page_id', 'isactive', 'sort_no', 'status'], 'integer'],
            [['news_date', 'effective_from', 'effective_till'], 'safe'],
            [['news_name', 'news_title', 'news_pict'], 'string', 'max' => 100],
            [['news_alt'], 'string', 'max' => 500],
            [['news_content'], 'string', 'max' => 5000],
            [['getfile'],'safe'],
            ['getfile',  'file', 'maxSize'=>'5000000', 'skipOnEmpty' => true, 'maxFiles' => 6],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => MasterCustomer::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['page_id'], 'exist', 'skipOnError' => true, 'targetClass' => MasterPages::className(), 'targetAttribute' => ['page_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('language', 'ID'),
            'customer_id' => Yii::t('language', 'Customer ID'),
            'page_id' => Yii::t('language', 'Page ID'),
            'news_name' => Yii::t('language', 'News Name'),
            'news_title' => Yii::t('language', 'News Title'),
            'news_content' => Yii::t('language', 'News Content'),
            'news_pict' => Yii::t('language', 'News Pict'),
            'news_alt' => Yii::t('language', 'News Alt'),
            'isactive' => Yii::t('language', 'Isactive'),
            'sort_no' => Yii::t('language', 'Sort No'),
            'news_date' => Yii::t('language', 'News Date'),
            'getfile'=>Yii::t('language', 'Picture'),
            'effective_from' => Yii::t('language', 'Effective From'),
            'effective_till' => Yii::t('language', 'Effective Till'),
            'createdby' => Yii::t('language', 'Createdby'),
            'createdon' => Yii::t('language', 'Createdon'),
            'lastmodifby' => Yii::t('language', 'Lastmodifby'),
            'lastmodif' => Yii::t('language', 'Lastmodif'),
            'status' => Yii::t('language', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedby0()
    {
        return $this->hasOne(CustUsers::className(), ['id' => 'createdby']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(MasterCustomer::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastmodifby0()
    {
        return $this->hasOne(CustUsers::className(), ['id' => 'lastmodifby']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPage()
    {
        return $this->hasOne(MasterPages::className(), ['id' => 'page_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterNewsPictures()
    {
        return $this->hasMany(MasterNewsPictures::className(), ['news_id' => 'id']);
    }
}

backend/controllers/MasterNewsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\MasterNews;
use common\models\MasterNewsSearch;
use common\models\MasterNewsPictures;
use common\models\MasterNewsPicturesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;
use yii\imagine\Image;

/**
 * MasterNewsController implements the CRUD actions for MasterNews model.
 */
class MasterNewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all MasterNews models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new MasterNewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single MasterNews model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "MasterNews #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                        'model3'=> MasterNewsPictures::find()->where(['news_id'=>$id])->all(),
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
                'model3' => MasterNewsPictures::find()->where(['news_id'=>$id])->all(),
            ]);
        }
    }

    public function actionUpload($id)
    {
        $model = new MasterNews();

        $file = UploadedFile::getInstances($model, 'getfile');

        if ($file !== false) {
            $sortno = 0;
            foreach ($file as $files) {
                $upload = new MasterNewsPictures();

                $upload->news_id = $id;
                $upload->sort_no = $sortno++;
                $upload->status = $sortno=1;
                $upload->picture_name = $files->name;
                $ext = end((explode(".", $files->name)));
                // generate a unique file name to prevent duplicate filenames
                $upload->picture_path = Yii::$app->security->generateRandomString().".{$ext}";
                // the path to save file, you can set an uploadPath
                // in Yii::$app->params (as used in example below)
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/uploads/news/';
                $path = Yii::$app->params['uploadPath'] . $upload->picture_path;
                $files->saveAs($path);

                $upload->save(false);

            }
        }
        else {
            $upload = new MasterNewsPictures();
            var_dump ($upload->getErrors()); die();
        }

        $this->redirect(['index']);
    }

    public function actionDeletepicture($id)
    {
        //$file_key = (int)\Yii::$app->request->post('id');
        $model3 = MasterNewsPictures::findOne($id);

        //$model2->delete();
        $path1 = Yii::$app->basePath . '/web/uploads/news/'.$model3->picture_path;

        if($model3->delete())
        {
            //for deleting picture from folder
            unlink($path1);

            //for result
            return true;
        }
        else
        {
            return false;
        }

        //return false;
    }

    /**
     * Creates a new MasterNews model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new MasterNews();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Create new MasterNews",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post())){
                $model->status = $model->status==1?10:0;
                $model->isactive = $model->isactive==1?10:0;

                $image = UploadedFile::getInstance($model, 'news_pict');
                if (!is_null($image)) {
                    $model->news_pict = $image->name;
                    $ext = end((explode(".", $image->name)));
                    // generate a unique file name to prevent duplicate filenames
                    $model->news_pict = Yii::$app->security->generateRandomString().".{$ext}";
                    // the path to save file, you can set an uploadPath
                    // in Yii::$app->params (as used in example below)
                    Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/uploads/news/';
                    $path = Yii::$app->params['uploadPath'] . $model->news_pict;
                    $image->saveAs($path);
                }

                if($model->validate() && $model->save())
                {
                    return [
                        'forceReload'=>'#crud-datatable-pjax',
                        'title'=> "Create new MasterNews",
                        'content'=>'<span class="text-success">Create MasterNews success</span>',
                        'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Create More',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])

                    ];
                }
                else
                {
                    return [
                        'title'=> "Create new MasterNews",
                        'content'=>$this->renderAjax('create', [
                            'model' => $model,
                        ]),
                        'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])

                    ];
                }
            }else{           
                return [
                    'title'=> "Create new MasterNews",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing MasterNews model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->status = $model->status==10?1:0;
        $model->isactive = $model->isactive==10?1:0;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Update MasterNews #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post())){
                $model->status = $model->status==1?10:0;
                $model->isactive = $model->isactive==1?10:0;

                if($model->validate())
                {
                    $model->news_pict = $model->news_pict=='' ? $model->oldAttributes['news_pict'] : $model->news_pict;
                    $image = UploadedFile::getInstance($model, 'news_pict');
                    if (!is_null($image)) {
                        $model->news_pict = $image->name;
                        $ext = end((explode(".", $image->name)));
                        // generate a unique file name to prevent duplicate filenames

backend/views/master-news/_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'customer_id',
        'value'=>'customer.customer_name'
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'page_id',
        'value'=>'page.page_name'
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'news_name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'news_title',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'news_content',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'news_pict',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'news_alt',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'isactive',
        'format'=>'html',
        'value'=>function($model)
        {
            return $model->isactive == 0 ? '<span class="label label-danger">Inactive</span>' : '<span class="label label-primary">Active</span>';
        },
        'filter' => [
            0 => 'Inactive',
            10 => 'Active'
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'sort_no',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'news_date',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'effective_from',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'effective_till',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'createdby',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'createdon',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'lastmodifby',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'lastmodif',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'format'=>'html',
        'value'=>function($model)
        {
            return $model->status == 0 ? '<span class="label label-danger">Inactive</span>' : '<span class="label label-primary">Active</span>';
        },
        'filter' => [
            0 => 'Inactive',
            10 => 'Active'
        ],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Are you sure?',
                          'data-confirm-message'=>'Are you sure want to delete this item'], 
    ],

];   

backend/views/master-news/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use vova07\select2\Widget;
use yii\web\JsExpression;
use kartik\widgets\SwitchInput;
use kartik\widgets\DateTimePicker;
use kartik\widgets\DatePicker;
use kartik\widgets\FileInput;
use yii\redactor\widgets\Redactor;

/* @var $this yii\web\View */
/* @var $model common\models\MasterNews */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="master-news-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php $dataCustomer = ArrayHelper::map(\common\models\MasterCustomer::find()->where(['status'=>10])->all(), 'id', 'customer_name'); ?>
    <?=
    $form->field($model, 'customer_id')->widget(Widget::classname(),[
        'items'=> $dataCustomer,
        'options'=>[
            'placeholder'=> 'Select Customer...'
        ],
        'events' => [
            'select2-open' => 'function (e) { log("select2:open", e); }',
            'select2-close' => new JsExpression('function (e) { log("select2:close", e); }')
        ],
        'settings' => [
            'width' => '100%',
        ],
    ]);
    ?>

    <?php $dataPage = ArrayHelper::map(\common\models\MasterPages::find()->where(['status'=>10])->all(), 'id', 'page_name'); ?>
    <?=
    $form->field($model, 'page_id')->widget(Widget::classname(),[
        'items'=> $dataPage,
        'options'=>['placeholder'=> 'Select Page...'],
        'events' => [
            'select2-open' => 'function (e) { log("select2:open", e); }',
            'select2-close' => new JsExpression('function (e) { log("select2:close", e); }')
        ],
        'settings' => [
            'width' => '100%',
        ],
    ]);
    ?>

    <?= $form->field($model, 'news_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'news_title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'news_content')->widget(Redactor::className(), [
    'clientOptions' => [
        'lang' => 'en-US',
        'limiter'=> 5000,
        'plugins' => ['fontcolor','limiter','textdirection','properties']
    ]
])?>


    <?= $form->field($model, 'news_pict')->widget(FileInput::classname(), [
    'options' => ['accept' => 'image/*'],
    'pluginOptions' => [
        'showCaption' => false,
        'showRemove' => false,
        'showUpload' => false,
        'browseClass' => 'btn btn-primary btn-block',
        'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
        'browseLabel' =>  'Select Photo',
        'initialPreview'=>[
            Html::img("@web/uploads/news/" . $model->news_pict,['width'=>100])
        ],
        'overwriteInitial'=>true
    ],
]); ?>

    <?= $form->field($model, 'news_alt')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isactive')->widget(SwitchInput::classname(),
    [
        'pluginOptions'=>[
            'onText'=>'Active',
            'offText'=>'Inactive',
        ],
    ]);
    ?>

    <?= $form->field($model, 'sort_no')->textInput() ?>

    <?= $form->field($model, 'news_date')->widget(DatePicker::classname(),
    [
        'name'=>'news_date',
        'value'=> date('yyyy-mm-dd'),
        'options'=>['placeholder'=>'Select a date...'],
        'pluginOptions'=>
        [
            'format'=>'yyyy-mm-dd',
            'todayHighlight'=>true,
            'autoclose'=>true,
        ]
    ]);
    ?>

    <?= $form->field($model, 'effective_from')->widget(DatetimePicker::classname(),
    [
        'name'=>'effective_from',
        'value'=> date('yyyy-mm-dd H:i:s'),
        'options'=>['placeholder'=>'Select a date...'],
        'pluginOptions'=>
        [
            'format'=>'yyyy-mm-dd H:i:s',
            'todayHighlight'=>true,
            'autoclose'=>true,
        ]
    ]);
    ?>

    <?= $form->field($model, 'effective_till')->widget(DatetimePicker::classname(),
    [
        'name'=>'effective_till',
        'value'=> date('yyyy-mm-dd H:i:s'),
        'options'=>['placeholder'=>'Select a date...'],
        'pluginOptions'=>
        [
            'format'=>'yyyy-mm-dd H:i:s',
            'todayHighlight'=>true,
            'autoclose'=>true,
        ]
    ]);
    ?>

    <?= $form->field($model, 'status')->widget(SwitchInput::classname(),
    [
        'pluginOptions'=>[
            'onText'=>'Active',
            'offText'=>'Inactive',
        ],
    ]);
    ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? Yii::t('language', 'Create') : Yii::t('language', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

backend/views/master-news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\MasterNews */

?>
<div class="master-news-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/master-news/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel common\models\MasterNewsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Master News';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="master-news-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Create new Master News','class'=>'btn btn-default']).
                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                    '{toggleData}'.
                    '{export}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'primary', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Master News listing',
                'before'=>'<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
                'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
                                ["bulk-delete"] ,
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Are you sure?',
                                    'data-confirm-message'=>'Are you sure want to delete this item'
                                ]),
                        ]).                        
                        '<div class="clearfix"></div>',
            ]
        ])?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

backend/views/master-news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MasterNews */
?>
<div class="master-news-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/master-news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\FileInput;
use Yii\helpers\Url;

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\MasterNews */
?>
<div class="master-news-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'customer.customer_name',
            'page.page_name',
            'news_name',
            'news_title',
            'news_content',
            'news_pict',
            'news_alt',
            [
                'label'=>'isactive',
                'format'=>'html',
                'attribute'=>function($model)
                {
                    if($model->isactive == 10)
                    {
                        return '<span class="label label-primary">'.'Active'.'</span>';
                    }
                    else
                    {
                        return "<span class='label label-danger'>"."Inactive"."</span>";
                    }
                }
            ],
            'sort_no',
            'effective_from',
            'effective_till',
            'createdby0.username',
            'createdon',
            'lastmodifby0.username',
            'lastmodif',
            [
                'label'=>'status',
                'format'=>'html',
                'attribute'=>function($model)
                {
                    if($model->status == 10)
                    {
                        return '<span class="label label-primary">'.'Active'.'</span>';
                    }
                    else
                    {
                        return "<span class='label label-danger'>"."Inactive"."</span>";
                    }
                }
            ],
        ],
    ]) ?>

    <?php $form = ActiveForm::begin([
    'options'=>['enctype'=>'multipart/form-data'], // important
    'action' =>['master-news/upload','id'=>$model->id],
    'id' => 'picture_post', 'method' => 'post',
]);?>

    <?php
    if($model3){
        $pictures = [];
        $picturesConfig = [];
        foreach ($model3 as $picture)
        {
            $pictures[] = Html::img("@web/uploads/news/" .$picture->picture_path ,['width'=>'70%']);
            $picturesConfig[] = [
                'caption'=>$picture->picture_name,
                'url'=> Url::to(['master-news/deletepicture','id'=>$picture->id]),
                'key'=>$picture->id,
            ];
        }
    }else{
        $pictures = "no_picture.jpg";
        $picturesConfig = "no config";
    }
    ?>

    <?= $form->field($model, 'getfile[]')->widget(FileInput::classname(), [
    'options' => ['multiple'=>true, 'accept' => 'image/*'],
    'pluginOptions' => [
        'showCaption' => true,
        'showRemove' => true,
        'showUpload' => false,
        'browseClass' => 'btn btn-primary btn-block',
        'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
        'browseLabel' =>  'Select Photo',
        'removeClass' => 'btn btn-danger',
        'removeIcon' => '<i class="glyphicon glyphicon-trash"></i>',
        'initialPreview'=>
        $pictures,
        'initialPreviewConfig'=>
        $picturesConfig,
        'overwriteInitial'=>false
    ],
]); ?>

    <div class="text-center col-lg-12">
        <div class="col-lg-12">
            <?= Html::submitButton('Upload', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>